name: generate_analysis_options
description: "An app to generate `analysis_options.yaml`."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-190.1.beta <4.0.0'

dependencies:
  backstreets_widgets: ^0.9.0
  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  file_picker: ^8.0.0+1
  flutter:
    sdk: flutter
  html: ^0.15.4
  url_launcher: ^6.2.5
  yaml: ^3.1.2
  yaml_writer: ^2.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
